"""Add generic reviews table and update collection frequency view

Revision ID: a275e20b090c
Revises: 3252097e86db
Create Date: 2026-03-03 22:03:08.056898

"""

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "a275e20b090c"
down_revision = "3252097e86db"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "reviews",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "reviewable_type",
            sa.Enum(
                "LABELSET", "CMS_CONTENT", "FLOW_DEFINITION", name="reviewabletype"
            ),
            nullable=False,
        ),
        sa.Column("reviewable_id", sa.String(), nullable=False),
        sa.Column("reviewer_user_id", sa.UUID(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("assessment", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["reviewer_user_id"],
            ["users.id"],
            name="fk_review_user",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reviews")),
        sa.UniqueConstraint(
            "reviewable_type",
            "reviewable_id",
            "reviewer_user_id",
            name="uq_reviews_type_entity_reviewer",
        ),
    )
    op.create_index(
        "ix_reviews_type_entity",
        "reviews",
        ["reviewable_type", "reviewable_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_reviews_type_entity", table_name="reviews")
    op.drop_table("reviews")
    # ### end Alembic commands ###
